package vues;

import java.util.ArrayList;
import javax.swing.*;
import models.Articles;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Samy
 */
public class Fen_Articles extends javax.swing.JInternalFrame {

    /**
     * Creates new form Fen_Articles
     */
    String code;
    public Fen_Articles() {
        initComponents();
        btn_modif.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_eng = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nom = new java.awt.TextField();
        btn_vider = new javax.swing.JButton();
        cat = new javax.swing.JComboBox();
        etat = new javax.swing.JComboBox();
        qte = new javax.swing.JComboBox();
        btn_fil = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_modif = new javax.swing.JButton();
        btn_liste = new javax.swing.JButton();
        btn_sup = new javax.swing.JButton();
        btn_rech = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Aharoni", 0, 20)); // NOI18N
        jLabel3.setText("Nom");

        jScrollPane2.setViewportView(jTextPane2);

        setBackground(new java.awt.Color(153, 153, 153));
        setClosable(true);
        setTitle("Gestion des Aticles");
        setToolTipText("La gestion des Aticles");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Gerer Articles", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Nom");

        btn_eng.setText("Enregistrer");
        btn_eng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_engActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setText("Categorie");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Etat");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Quantite");

        nom.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        btn_vider.setText("Vider");
        btn_vider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viderActionPerformed(evt);
            }
        });
        
        cat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "","Informatque", "Telecom", "Ingenerie", "Architecture" }));
        cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catActionPerformed(evt);
            }
        });

        etat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Neuf", "Usé", "Defectueux" }));

        qte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        for (int i = 1; i <= 1000 ; i++){
            //String val = i.toString();
            qte.addItem(Integer.toString(i));
        }
        //qte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "","1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        btn_fil.setText("Filiere");
        btn_fil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(54, 54, 54)
                        .addComponent(qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cat, javax.swing.GroupLayout.Alignment.LEADING, 0, 285, Short.MAX_VALUE)
                            .addComponent(nom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btn_eng)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_vider, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_fil)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(qte, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_eng, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_fil, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_vider, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btn_modif.setText("Modifier");
        btn_modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifActionPerformed(evt);
            }
        });

        btn_liste.setText("Lister");
        btn_liste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listeActionPerformed(evt);
            }
        });

        btn_sup.setText("Supprimer");
        btn_sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supActionPerformed(evt);
            }
        });

        btn_rech.setText("Rechercher");
        btn_rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rechActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btn_rech)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_modif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_liste)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sup)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_rech, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
            .addComponent(btn_modif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_liste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_sup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/LOGO.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-473)/2, (screenSize.height-428)/2, 473, 428);
    }// </editor-fold>

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void btn_engActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
            String nom_art = nom.getText();
              String cat_art = cat.getSelectedItem().toString();
              String etat_art = etat.getSelectedItem().toString();
              int qte_art = Integer.parseInt(qte.getSelectedItem().toString());
              
              Articles art = new Articles(nom_art,cat_art,etat_art,qte_art);
              String rep  = art.enregistrer_Articles();
              //JOptionPane.showMessageDialog(this,rep);
              if (rep.equalsIgnoreCase("ouverture nok")){
                    JOptionPane.showMessageDialog(this,"La connexiona a la base a echoue!!!");
              }else if(rep.equalsIgnoreCase("succes")){
                        JOptionPane.showMessageDialog(this,"Aricles enregistre avec succes !!!");
                    }else{
                       JOptionPane.showMessageDialog(this,"Enregistrement echoue  !!!");
                    }

    }                                       

    private void catActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   
    
    private void btn_ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }        
    
    private void btn_listeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Fen_lister_Art liste = new Fen_lister_Art();
        liste.setVisible(true);
        liste.toFront();
    }
    
    private void btn_supActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
       String rep = "";
       Articles at = new Articles();
       String code  =  JOptionPane.showInputDialog(null, "Veuillez entrer le code d'article à supprimer : ", "Supprimer Articles",JOptionPane.QUESTION_MESSAGE);
       if ((code == null) || (code.equalsIgnoreCase(""))){
        
        }else{
            int option = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer l'article ?", "Lancement de la suppression", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if ((option == JOptionPane.NO_OPTION) || (option == JOptionPane.CANCEL_OPTION) || (option == JOptionPane.CLOSED_OPTION)){
                
            }else{
                String r = at.supprimer_Articles(code);
                              
                if (r.equalsIgnoreCase("kod la pa bon !")){
                    JOptionPane.showMessageDialog(this,"Code invalide!!");
                }else
                    if (r.equalsIgnoreCase("succes")){
                        JOptionPane.showMessageDialog(this,"Suppression effectuée avec succes!!");
                  
                    }else{
                           JOptionPane.showMessageDialog(this,"Suppression echouée !!!!");
                    }
                   
            }
        }
    }
    
    private void btn_rechActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        btn_modif.setEnabled(true);
        btn_eng.setEnabled(false);
        this.code  =  JOptionPane.showInputDialog(null, "Veuillez entrer le code d'article a rechercher : ", "Rechercher Articles",JOptionPane.QUESTION_MESSAGE);
        Articles at = new Articles();
         if ((code == null) || (code.equalsIgnoreCase(""))){
              
            }else{
                       ArrayList rech =  at.rechecher_Articles(this.code);
                      if ((rech.get(0).toString()).equalsIgnoreCase("kod la pa bon !")){
                           JOptionPane.showMessageDialog(this,"Code invalide!!!", "Erreur",JOptionPane.ERROR_MESSAGE);
                      }else{
                         nom.setText(rech.get(1).toString());
                         cat.setSelectedItem(rech.get(2).toString());
                         etat.setSelectedItem(rech.get(3).toString());
                         qte.setSelectedItem(rech.get(5).toString());
                      
                      }
              }
        
    }                                        

    private void btn_modifActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
         //String code  =  JOptionPane.showInputDialog(null, "Veuillez entrer le code d'article a rechercher : ", "Rechercher Articles",JOptionPane.QUESTION_MESSAGE);
          String nom_art = nom.getText();
            String cat_art = cat.getSelectedItem().toString();
            String etat_art = etat.getSelectedItem().toString();
            int qte_art = Integer.parseInt(qte.getSelectedItem().toString()); 
            Articles art = new Articles(nom_art,cat_art,etat_art,qte_art);
             String mod =  art.modifier_Articles(this.code);
                if (mod.equalsIgnoreCase("kod la pa bon !")){
                     JOptionPane.showMessageDialog(this,"Code invalide!!!", "Erreur",JOptionPane.ERROR_MESSAGE);
                 }else
                     if(mod.equalsIgnoreCase("echoue")){
                        JOptionPane.showMessageDialog(this,"Modification echouée !!!", "Erreur",JOptionPane.ERROR_MESSAGE);
                     }else{
                        JOptionPane.showMessageDialog(this,"Modification reussie  !!!", "Information", JOptionPane.INFORMATION_MESSAGE);
                 }
               btn_modif.setEnabled(false);
               btn_eng.setEnabled(true);
               this.code = "";
    }                                         
    
    private void btn_viderActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        nom.setText("");
        cat.setSelectedItem("");
        etat.setSelectedItem("");
        qte.setSelectedItem("1");
        btn_modif.setEnabled(false);
        btn_eng.setEnabled(true);
    }
    
    private void btn_filActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        fen_art_fil l = new fen_art_fil();
        l.setVisible(true);
        l.toFront();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btn_eng;
    private javax.swing.JButton btn_fil;
    private javax.swing.JButton btn_liste;
    private javax.swing.JButton btn_modif;
    private javax.swing.JButton btn_rech;
    private javax.swing.JButton btn_sup;
    private javax.swing.JButton btn_vider;
    private javax.swing.JComboBox cat;
    private javax.swing.JComboBox etat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane2;
    private java.awt.TextField nom;
    private javax.swing.JComboBox qte;
    // End of variables declaration
}
