package vues;

import javax.swing.JOptionPane;
import models.Deplacement;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Samy
 */
public class Fen_liste_depl extends javax.swing.JFrame {

    /**
     * Creates new form Fen_liste_depl
     */
    public Fen_liste_depl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_rech = new java.awt.TextField();
        btn_rech = new javax.swing.JButton();
        btn_vider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/LOGO-icone3.png")).getImage());
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/LOGO-liste_depl.jpg"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Deplacement().lister_Deplacement(),
            new String [] {
                "Code", "Nom article", "Magasin", "Quantite", "quantite deplace", "Personne", "Etat", "Date deplacement", "Date retour"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Rechercher un article");

        btn_rech.setText("Rechercher");
        btn_rech.addActionListener(new java.awt.event.ActionListener() {
            @Override
          public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rechActionPerformed(evt);
          }
        });

        btn_vider.setText("Vider");
        btn_vider.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_rech, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_rech)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_vider)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addComponent(jSeparator1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(btn_rech, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addComponent(btn_vider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txt_rech, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-782)/2, (screenSize.height-582)/2, 782, 582);
    }// </editor-fold>

     private void btn_rechActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String nom = txt_rech.getText();
        
        if (nom.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this,"Vous devez entrer un valeur dans le champs!!!", "Erreur",JOptionPane.ERROR_MESSAGE);
        }else{
               JOptionPane.showMessageDialog(this,new Deplacement().lister_Deplacement(nom).length, "Information",JOptionPane.INFORMATION_MESSAGE);
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Deplacement().lister_Deplacement(nom),
            new String [] {
                "Codes", "Nom article", "Magasin", "Quantite", "quantite deplace", "Personne", "Etat", "Date deplacement", "Date retour"
            }
           ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

               @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
          });
            jScrollPane1.setViewportView(jTable1);
        }
    }

    private void btn_viderActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        txt_rech.setText("");
    }
    
    
    // Variables declaration - do not modify
    private javax.swing.JButton btn_rech;
    private javax.swing.JButton btn_vider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private java.awt.TextField txt_rech;
    // End of variables declaration
}
