package vues;

import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import models.Retour;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Samy
 */
public class Fen_Retour extends javax.swing.JInternalFrame {
    
    private String code;
    private int qte;
    
    /**
     * Creates new form Fen_Retour
     */
    public Fen_Retour() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_code = new javax.swing.JLabel();
        lb_nom = new javax.swing.JLabel();
        lb_date_dpl = new javax.swing.JLabel();
        lb_date_rt = new javax.swing.JLabel();
        lb_anx = new javax.swing.JLabel();
        lb_qte = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Date maDate=new Date(); 
        SimpleDateFormat date_st = new SimpleDateFormat("dd/MM/yyyy");
        date_retour = new java.awt.TextField(date_st.format(maDate));
        date_retour.setEditable(false);
        txt_nom = new java.awt.TextField();
        qte_ret = new javax.swing.JComboBox();
        qte_ut = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        qte_def = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_com = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_ver = new javax.swing.JButton();
        btn_ret = new javax.swing.JButton();
        btn_ann = new javax.swing.JButton();
        btn_lister = new javax.swing.JButton();
        btn_vider = new javax.swing.JButton();
        btn_imp = new javax.swing.JButton();

        jLabel14.setText("jLabel14");

        setClosable(true);
        setTitle("Retour d'un article");
        setToolTipText("Retour d'un article");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/LOGO-icone.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)), "Informations Sur l'article deplacé", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14), java.awt.Color.blue)); // NOI18N

        jLabel2.setText("Code : ");

        jLabel3.setText("Nom : ");

        jLabel4.setText("Date du deplacement : ");

        jLabel5.setText("Quantités deplacées : ");

        jLabel6.setText("Annexe : ");

        jLabel7.setText("Date Retour : ");

        lb_code.setForeground(new java.awt.Color(255, 0, 255));

        lb_nom.setForeground(new java.awt.Color(255, 0, 255));

        lb_date_dpl.setForeground(new java.awt.Color(204, 0, 204));

        lb_date_rt.setForeground(new java.awt.Color(204, 0, 204));

        lb_anx.setForeground(new java.awt.Color(204, 0, 204));

        lb_qte.setForeground(new java.awt.Color(204, 0, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_date_dpl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_code, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_anx, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_date_rt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(lb_code)
                    .addComponent(lb_qte))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(lb_nom)
                    .addComponent(lb_anx))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(lb_date_dpl)
                    .addComponent(lb_date_rt))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)), "Retour d'article deplacé", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14), java.awt.Color.blue)); // NOI18N

        jLabel8.setText("Date du retour");

        jLabel9.setText("Nom");

        jLabel10.setText("Quantités retournées");

        jLabel11.setText("Quantités Utilisables");
        
        for (int i = 1; i <= 20  ; i++){
            //String val = i.toString();
            qte_ret.addItem(Integer.toString(i));
        }
        //qte_ret.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        
        for (int i = 0; i <= 1000 ; i++){
            //String val = i.toString();
            qte_ut.addItem(Integer.toString(i));
        }
        //qte_ut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        qte_ut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qte_utActionPerformed(evt);
            }
        });

        jLabel12.setText("Quantités defectueuses");

        //qte_def.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        for (int i = 0; i <= 20 ; i++){
            //String val = i.toString();
            qte_def.addItem(Integer.toString(i));
        }
        
        jLabel13.setText("Commentaire");

        jScrollPane1.setViewportView(txt_com);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(qte_def, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(qte_ret, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(qte_ut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addComponent(txt_nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date_retour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(qte_def, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(date_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(qte_ret, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(qte_ut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(51, 51, 51))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/LOGO-retour.jpg"))); // NOI18N
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51)));

        btn_ver.setText("Verifier");
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });

        btn_ret.setText("Retourner");
        btn_ret.setEnabled(false);
        btn_ret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retActionPerformed(evt);
            }
        });

        btn_ann.setText("Annuler");
        btn_ann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annActionPerformed(evt);
            }
        });

        btn_lister.setText("Lister");
        btn_lister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listerActionPerformed(evt);
            }
        });

        btn_vider.setText("Vider");
        btn_vider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viderActionPerformed(evt);
            }
        });

        btn_imp.setText("Imprimer");
        btn_imp.setEnabled(false);
        btn_imp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_impActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_imp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_vider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ret)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ann)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_lister)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ver)
                    .addComponent(btn_ret)
                    .addComponent(btn_ann)
                    .addComponent(btn_lister)
                    .addComponent(btn_vider)
                    .addComponent(btn_imp))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void qte_utActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void btn_impActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Retour rt = new Retour();
        String[] data = {lb_code.getText(), lb_date_dpl.getText(), date_retour.getText(), lb_anx.getText().toString(),lb_qte.getText(), txt_nom.getText(), lb_nom.getText(), txt_com.getText(), qte_ret.getSelectedItem().toString(), qte_ut.getSelectedItem().toString(), qte_def.getSelectedItem().toString()};
        rt.imprimer_dpl(data);
        btn_imp.setEnabled(false);
     }

    private void btn_viderActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        txt_com.setText("");
        qte_def.setSelectedItem(0);
        qte_ut.setSelectedItem(0);
        qte_ret.setSelectedItem(1);
        txt_nom.setText("");
    }

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.code  =  JOptionPane.showInputDialog(null, "Veuillez entrer le code d'article deplacé a rechercher : ", "Rechercher Articles", JOptionPane.QUESTION_MESSAGE);
         Retour rt = new Retour();
         if ((this.code == null) || (code.equalsIgnoreCase(""))){
              
            }else{
                       ArrayList dsp =  rt.verifier_Art_Deplacer(this.code);
                        //JOptionPane.showMessageDialog(this,dsp.size(), "Erreur",JOptionPane.ERROR_MESSAGE);
                                           
                        if(dsp.get(0).toString().equalsIgnoreCase("")){
                            JOptionPane.showMessageDialog(this,"code invalid ou Cet article est deja retourné, verifiez svp!!!", "Erreur",JOptionPane.ERROR_MESSAGE);
                      }else{
                                                   
                          lb_code.setText(dsp.get(0).toString());                          
                          lb_nom.setText(dsp.get(1).toString());
                          lb_anx.setText(dsp.get(2).toString());
                          lb_date_dpl.setText(dsp.get(3).toString());
                          lb_date_rt.setText(dsp.get(4).toString());
                          lb_qte.setText(dsp.get(5).toString());
                          this.qte = Integer.parseInt(dsp.get(5).toString());
                          btn_ret.setEnabled(true);
                          btn_imp.setEnabled(true);
                        }
              }
    }

    private void btn_retActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
           int qut = Integer.parseInt(qte_ut.getSelectedItem().toString());
        int qrt = Integer.parseInt(qte_ret.getSelectedItem().toString());
        int qdef = Integer.parseInt(qte_def.getSelectedItem().toString());
        int lb_q = Integer.parseInt(lb_qte.getText());
        if( qrt > lb_q){
            JOptionPane.showMessageDialog(this,"La quatite retournée doit etre inferieure a la qte déplacée!!! ", "Erreur",JOptionPane.ERROR_MESSAGE);
        }else if( (qut + qdef) > qrt){
            JOptionPane.showMessageDialog(this,"La somme de la quantite utilisable et defecteuse doit etre inferieure ou egale a la qte retournée!!! ", "Erreur",JOptionPane.ERROR_MESSAGE);
        }else if ((txt_nom.getText().equals("")) || (qrt == 0)){
            JOptionPane.showMessageDialog(this,"Certains champs ne doivent pas etre null ou egal a zero!! ", "Erreur",JOptionPane.ERROR_MESSAGE);
        }else{
                Retour rt = new Retour(this.code, date_retour.getText(),txt_nom.getText(), qrt, qut, qdef, txt_com.getText());
                    String rep = rt.retour_Article();
                    if (rep.equalsIgnoreCase("ouveti a pa bon")){
                        JOptionPane.showMessageDialog(this,"Connexion a la base nok!!", "Erreur",JOptionPane.ERROR_MESSAGE);
                    }else
                        if(rep.equalsIgnoreCase("code invalid")){
                            JOptionPane.showMessageDialog(this,"Le code d'article est invalid", "Erreur",JOptionPane.ERROR_MESSAGE);
                        }else
                              if(rep.equalsIgnoreCase("echec")){
                                JOptionPane.showMessageDialog(this,"Retour d'article echoué !!!", "Erreur",JOptionPane.ERROR_MESSAGE);
                            }else{
                                JOptionPane.showMessageDialog(this,"Retour d'article effectué avec succes !!!", "Erreur",JOptionPane.INFORMATION_MESSAGE);
                                btn_ret.setEnabled(false);
                                
                            }
                            
        }
    }

    private void btn_annActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
       String rep = "";
       Retour ret = new Retour();
       String code  =  JOptionPane.showInputDialog(null, "Veuillez entrer le code du deplacement à annuler : ", "Annuler un deplacement",JOptionPane.QUESTION_MESSAGE);
       if ((code == null) || (code.equalsIgnoreCase(""))){
        
        }else{
            int option = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer l'article ?", "Lancement de la suppression", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if ((option == JOptionPane.NO_OPTION) || (option == JOptionPane.CANCEL_OPTION) || (option == JOptionPane.CLOSED_OPTION)){
                
            }else{
                String r = ret.annuler_Retour(code);
                              
                if (r.equalsIgnoreCase("kod la pa bon !")){
                    JOptionPane.showMessageDialog(this,"Code invalide!!");
                }else
                    if (r.equalsIgnoreCase("succes")){
                        JOptionPane.showMessageDialog(this," Annulation du retour d'article effectuée avec succes!!");
                  
                    }else{
                           JOptionPane.showMessageDialog(this,"Echec de l'annulation d'un retour d'article!!!!");
                    }
                   
            }
        }
        
    }

    private void btn_listerActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Fen_liste_retour liste = new Fen_liste_retour();
        liste.setVisible(true);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btn_ann;
    private javax.swing.JButton btn_imp;
    private javax.swing.JButton btn_lister;
    private javax.swing.JButton btn_ret;
    private javax.swing.JButton btn_ver;
    private javax.swing.JButton btn_vider;
    private java.awt.TextField date_retour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_anx;
    private javax.swing.JLabel lb_code;
    private javax.swing.JLabel lb_date_dpl;
    private javax.swing.JLabel lb_date_rt;
    private javax.swing.JLabel lb_nom;
    private javax.swing.JLabel lb_qte;
    private javax.swing.JComboBox qte_def;
    private javax.swing.JComboBox qte_ret;
    private javax.swing.JComboBox qte_ut;
    private javax.swing.JTextPane txt_com;
    private java.awt.TextField txt_nom;
    // End of variables declaration
}
