package vues;

import java.util.ArrayList;
import javax.swing.*;
import java.text.*;
import javax.swing.text.MaskFormatter; 
import java.util.Date;
import java.awt.*;
import models.Deplacement;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Samy
 */
public class Fen_Mouv extends javax.swing.JInternalFrame {
    private String code = "";

    /**
     * Creates new form Fen_Mouv
     */
    public Fen_Mouv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        try
            {
               MaskFormatter mask = new MaskFormatter("##/##/####");
               mask.setValidCharacters("0123456789");
               txt_date_r = new javax.swing.JFormattedTextField(mask);
            }
            catch (ParseException e)
            {
            }
        Date maDate=new Date(); 
        SimpleDateFormat date_st = new SimpleDateFormat("dd/MM/yyyy"); 
        txt_date_dpl = new javax.swing.JFormattedTextField(date_st.format(maDate));
        txt_date_dpl.setEnabled(false);
        annexe = new javax.swing.JComboBox();
        qte = new java.awt.Choice();
        jLabel6 = new javax.swing.JLabel();
        txt_nom = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_dsp = new javax.swing.JButton();
        btn_ann = new javax.swing.JButton();
        btn_lister = new javax.swing.JButton();
        btn_Déplacé = new javax.swing.JButton();
        btn_vide = new javax.swing.JButton();
        btn_imp = new javax.swing.JButton();
        btn_imp.setEnabled(false);
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lb_code_art = new javax.swing.JLabel();
        lb_nom_art = new javax.swing.JLabel();
        lb_qte = new javax.swing.JLabel();
        lb_cat = new javax.swing.JLabel();
        lb_etat = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel15.setText("jLabel15");

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setTitle("Deplacement Articles");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/LOGO-icone.png")));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.white), "Deplacement d'Article", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Date du depalcement");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("Annexe");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Quantité deplacée");

            annexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"", "Cayes", "Jacmel", "Cap", "Gonaives" }));

        qte.setName(""); // NOI18N
        for (int i = 1; i <= 1000 ; i++){
            //String val = i.toString();
            qte.addItem(Integer.toString(i));
        }

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Nom personne");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Date retour");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_date_dpl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(annexe, 0, 233, Short.MAX_VALUE)
                    .addComponent(qte, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_date_r, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txt_date_dpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_date_r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annexe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btn_dsp.setText("disponibilité");
        btn_dsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dspActionPerformed(evt);
            }
        });

        btn_ann.setText("Annuler");
        btn_ann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annActionPerformed(evt);
            }
        });

        btn_lister.setText("Lister");
        btn_lister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listerActionPerformed(evt);
            }
        });

        btn_Déplacé.setText("Déplacé");
        btn_Déplacé.setSelected(false);
        btn_Déplacé.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DéplacéActionPerformed(evt);
            }
        });

        btn_vide.setText("vider");
        btn_vide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_videActionPerformed(evt);
            }
        });

        btn_imp.setText("Imprimer");
        btn_imp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_impActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_dsp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_imp)
                .addGap(18, 18, 18)
                .addComponent(btn_Déplacé)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_vide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ann)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_lister)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ann)
                    .addComponent(btn_lister)
                    .addComponent(btn_Déplacé)
                    .addComponent(btn_vide)
                    .addComponent(btn_imp)
                    .addComponent(btn_dsp))
                .addContainerGap())
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/LOGO-depl.jpg"))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.white), "Inforamtions sur l'article", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, java.awt.Color.blue));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Code :");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Nom :");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Quantite :");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Categorie : ");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Etat :");

        lb_code_art.setBackground(new java.awt.Color(0, 0, 255));
        lb_code_art.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lb_code_art.setForeground(new java.awt.Color(153, 0, 0));
        lb_code_art.setText("jLabel2");

        lb_nom_art.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lb_nom_art.setForeground(new java.awt.Color(153, 0, 0));
        lb_nom_art.setText("jLabel7");

        lb_qte.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lb_qte.setForeground(new java.awt.Color(153, 0, 0));
        lb_qte.setText("jLabel14");

        lb_cat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lb_cat.setForeground(new java.awt.Color(153, 0, 0));
        lb_cat.setText("jLabel16");

        lb_etat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lb_etat.setForeground(new java.awt.Color(153, 0, 0));
        lb_etat.setText("jLabel17");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(lb_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_code_art, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_nom_art, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lb_etat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(lb_code_art)
                    .addComponent(lb_cat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(lb_nom_art)
                    .addComponent(lb_etat))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lb_qte))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>

    private void btn_DéplacéActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        
        if((txt_date_r.getText().equals("")) || (annexe.getSelectedItem().toString().equals("")) || (txt_nom.getText().equals(""))){
            JOptionPane.showMessageDialog(this,"Veuillez remplir tous les champs svp !!!", "Erreur",JOptionPane.ERROR_MESSAGE);
        }else{
            int q = Integer.parseInt(qte.getSelectedItem().toString());
            Deplacement dpl = new Deplacement(this.code,txt_date_dpl.getText(),txt_date_r.getText(),annexe.getSelectedItem().toString(),q,txt_nom.getText());
            String rep = dpl.deplacer_Article();
            if (rep.equalsIgnoreCase("code invalid")){
                JOptionPane.showMessageDialog(this,"Le code d'article est invalid", "Erreur",JOptionPane.ERROR_MESSAGE);
            }else
                if(rep.equalsIgnoreCase("qte deplace superieur")){
                    JOptionPane.showMessageDialog(this,"La quantite deplacée doit etre inferieur a la quantite stockée", "Erreur",JOptionPane.ERROR_MESSAGE);
                }else
                if(rep.equalsIgnoreCase("date invalide")){
                    JOptionPane.showMessageDialog(this,"La date de retour doit etre superieur a la date de deplacement !!!", "Erreur",JOptionPane.ERROR_MESSAGE);
                }else
                    if(rep.equalsIgnoreCase("echec")){
                    JOptionPane.showMessageDialog(this,"Deplacement echoué !!!", "Erreur",JOptionPane.ERROR_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this,"Deplacement effectué avec succes !!!", "Erreur",JOptionPane.INFORMATION_MESSAGE);
                    btn_Déplacé.setEnabled(false);
                    btn_imp.setEnabled(true);
                    
                }
        }
    }                                           

    private void btn_videActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        btn_Déplacé.setEnabled(false);
         btn_imp.setEnabled(false);
        //txt_date_dpl.setText("");    
        txt_date_r.setText("");
        annexe.setSelectedItem("");
        qte.select(0);
        txt_nom.setText("");
        
    }                                        

    private void btn_dspActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        String nom  =  JOptionPane.showInputDialog(null, "Veuillez entrer le code d'article a rechercher : ", "Rechercher Articles", JOptionPane.QUESTION_MESSAGE);
         Deplacement dpl = new Deplacement();
         if ((nom == null) || (nom.equalsIgnoreCase(""))){
              
            }else{
                       ArrayList dsp =  dpl.Disponibilite_art(nom);
                        //JOptionPane.showMessageDialog(this,dsp.size(), "Erreur",JOptionPane.ERROR_MESSAGE);
                       
                      if (dsp == null){
                           JOptionPane.showMessageDialog(this,"quantite indisponible !!!", "Erreur",JOptionPane.ERROR_MESSAGE);
                      }else
                        if(dsp.get(0).toString().equalsIgnoreCase("")){
                            JOptionPane.showMessageDialog(this,"code invalid !!!", "Erreur",JOptionPane.ERROR_MESSAGE);
                      }else{
                          lb_code_art.setText(dsp.get(0).toString());  
                          this.code = dsp.get(0).toString();
                          lb_nom_art.setText(dsp.get(1).toString());
                          lb_qte.setText(dsp.get(4).toString());
                          lb_cat.setText(dsp.get(2).toString());
                          lb_etat.setText(dsp.get(3).toString());
                             
                          btn_Déplacé.setEnabled(true);
                        }
              }
    }                                       

    private void btn_annActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        String rep = "";
       Deplacement dpl = new Deplacement();
       String code  =  JOptionPane.showInputDialog(null, "Veuillez entrer le code du deplacement à annuler : ", "Annuler un deplacement",JOptionPane.QUESTION_MESSAGE);
       if ((code == null) || (code.equalsIgnoreCase(""))){
        
        }else{
            int option = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer l'article ?", "Lancement de la suppression", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if ((option == JOptionPane.NO_OPTION) || (option == JOptionPane.CANCEL_OPTION) || (option == JOptionPane.CLOSED_OPTION)){
                
            }else{
                String r = dpl.annuler_Deplacement(code);
                              
                if (r.equalsIgnoreCase("kod la pa bon !")){
                    JOptionPane.showMessageDialog(this,"Code invalide!!");
                }else
                    if (r.equalsIgnoreCase("succes")){
                        JOptionPane.showMessageDialog(this,"Deplacement annulé effectuée avec succes!!");
                        
                    }else{
                           JOptionPane.showMessageDialog(this,"Echec de l'annulation d'un deplacement!!!!");
                    }
                   
            }
        }
    }                                       

    private void btn_listerActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Fen_liste_depl liste = new Fen_liste_depl();
        liste.setVisible(true);
    }                                          

    private void btn_impActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Deplacement dpl = new Deplacement();
        String[] data = {lb_code_art.getText(), txt_date_dpl.getText(), txt_date_r.getText(), annexe.getSelectedItem().toString(),qte.getSelectedItem().toString(), txt_nom.getText(), lb_nom_art.getText(), lb_etat.getText()};
        dpl.imprimer_dpl(data);
        btn_imp.setEnabled(false);
        txt_date_r.setText("");
        annexe.setSelectedItem("");
        qte.select(0);
        txt_nom.setText("");
    }

    // Variables declaration - do not modify
    private javax.swing.JComboBox annexe;
    private javax.swing.JButton btn_Déplacé;
    private javax.swing.JButton btn_ann;
    private javax.swing.JButton btn_dsp;
    private javax.swing.JButton btn_imp;
    private javax.swing.JButton btn_lister;
    private javax.swing.JButton btn_vide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lb_cat;
    private javax.swing.JLabel lb_code_art;
    private javax.swing.JLabel lb_etat;
    private javax.swing.JLabel lb_nom_art;
    private javax.swing.JLabel lb_qte;
    private java.awt.Choice qte;
    private javax.swing.JFormattedTextField txt_date_dpl;
    private javax.swing.JFormattedTextField txt_date_r;
    private java.awt.TextField txt_nom;
    // End of variables declaration
}
