package vues;

import java.awt.*;
import javax.swing.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Samy
 */
public class Fen_Principale extends javax.swing.JFrame {

    /**
     * Creates new form Fen_Principale
     */
    public Fen_Principale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Men_mouvement = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        dsp = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAGASIN IDEJEN");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/LOGO-icone3.png")).getImage());
        
        //jDesktopPane1.setBackground(new java.awt.Color(0, 51, 204));
        jDesktopPane1.setToolTipText("");
        jDesktopPane1.setName("dkp"); // NOI18N

        jMenu1.setText("Fichier");

        //jMenuItem10.setText("Ouvrir");
        //jMenu1.add(jMenuItem10);

        jMenuItem11.setText("Fermer");
        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
       // jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/applications-icone-8288-32.png")));
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edition");

        jMenuItem5.setText("Annuler");
        //jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/undo.png"))); 
        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Couper");
        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
      //  jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/cut.png"))); 
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Copier");
        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
      //  jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/copy.png")));
        jMenu2.add(jMenuItem7);
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jMenuItem7ActionPerformed(evt);
            }
        });

        jMenuItem8.setText("Coller");
        //jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/coller.png")));
        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenu2.add(jMenuItem8);
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jMenuItem8ActionPerformed(evt);
            }
        });
        
        jMenu2.add(jSeparator1);

        jMenuItem9.setText("Selectionner");
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Services");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        
        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Articles");
        jMenuItem1.setName("Men_Art"); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/article.png")));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);
        
        Men_mouvement.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        Men_mouvement.setText("Deplacement");
       Men_mouvement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/deplacement.png")));
        Men_mouvement.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Men_mouvementActionPerformed(evt);
            }
        });
        jMenu3.add(Men_mouvement);
        
        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Retour");
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/retour.png")));
        jMenu3.add(jMenuItem3);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Filiere");
       jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/fil.png")));
        jMenu3.add(jMenuItem4);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Rapports");
        
        dsp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        dsp.setText("Liste des Articles disponible");
        dsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/liste.png")));
        jMenu4.add(dsp);
        dsp.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dspActionPerformed(evt);
            }
        });
        
        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setText("Resumé stock");
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/qte.png")));
        jMenu4.add(jMenuItem13);
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDesktopPane1.getAccessibleContext().setAccessibleName("dkp");

        getAccessibleContext().setAccessibleName("idejen");
        getAccessibleContext().setAccessibleParent(this);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-791)/2, (screenSize.height-680)/2, 791, 680);
    }// </editor-fold>

public void centerJIF(JInternalFrame jif) {
    Dimension desktopSize = jDesktopPane1.getSize();
    Dimension jInternalFrameSize = jif.getSize();
    int width = (desktopSize.width - jInternalFrameSize.width) / 2;
    int height = (desktopSize.height - jInternalFrameSize.height) / 2;
    jif.setLocation(width, height);
    jif.setVisible(true);
    jif.toFront();
}
    private void Men_mouvementActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Fen_Mouv  mouv = new Fen_Mouv() ;
        jDesktopPane1.add(mouv);
         centerJIF(mouv);
      
    } 
    
     private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Fen_Retour  rt = new Fen_Retour() ;
        jDesktopPane1.add(rt);
         centerJIF(rt);
      
    }
    
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Fen_filiere  fil = new Fen_filiere() ;
        jDesktopPane1.add(fil);
         centerJIF(fil);
      
    }
    
    private void jMen3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Fen_Retour  rt = new Fen_Retour() ;
        jDesktopPane1.add(rt);
         centerJIF(rt);
      
    }         

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Fen_Articles  art = new Fen_Articles() ;
        jDesktopPane1.add(art);
        centerJIF(art);
     
    }                                          

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }
    
    private void dspActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        Fen_lister_Art liste = new Fen_lister_Art();
        liste.setVisible(true);
        liste.toFront();
    }        

    /**
     * @param args the command line arguments
     */
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
               
    }
    
     private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        
      
    }
 
    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Fen_Resume_stk rs = new Fen_Resume_stk();
        //rs.setRelativeTo();
        rs.setVisible(true);
        
    }    
    
       // Variables declaration - do not modify
    private javax.swing.JMenuItem Men_mouvement;
    private javax.swing.JMenuItem dsp;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration
}
