package vues;

import javax.swing.JOptionPane;
import models.Retour;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Samy
 */
public class Fen_liste_retour extends javax.swing.JFrame {

    /**
     * Creates new form Fen_liste_retour
     */
    public Fen_liste_retour() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_retour = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_rech = new java.awt.TextField();
        btn_rech = new javax.swing.JButton();
        btn_vider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Liste des articles retournés");
        setResizable(false);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/LOGO-icone3.png")).getImage());

        tb_retour.setModel(new javax.swing.table.DefaultTableModel(
            new Retour().lister_Retour(),
            new String [] {
                "Code", "Articles", "Date Retour", "Quantites", "Qte Utilisables", "Qte defectueuses", "Personnes", "Commentaires"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_retour.setFocusTraversalPolicyProvider(true);
        tb_retour.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tb_retour);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iedejen/ressource/LOGO-retour2.jpg"))); // NOI18N

        jLabel2.setText("Entrez l'article a rechercher : ");

        btn_rech.setText("Rechercher");
        btn_rech.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rechActionPerformed(evt);
            }
        });

        btn_vider.setText("Vider");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_rech, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_rech)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_vider)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_rech, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_rech)
                        .addComponent(btn_vider)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-717)/2, (screenSize.height-474)/2, 717, 474);
    }// </editor-fold>

    private void btn_rechActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String nom = txt_rech.getText();
        
        if (nom.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this,"Vous devez entrer un valeur dans le champs!!!", "Erreur",JOptionPane.ERROR_MESSAGE);
        }else{
             tb_retour.setModel(new javax.swing.table.DefaultTableModel(
            new Retour().lister_Retour(nom),
            new String [] {
                "Code", "Articles", "Date Retour", "Quantites", "Qte Utilisables", "Qte defectueuses", "Personnes", "Commentaires"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_retour);
        }
    }

    
    // Variables declaration - do not modify
    private javax.swing.JButton btn_rech;
    private javax.swing.JButton btn_vider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_retour;
    private java.awt.TextField txt_rech;
    // End of variables declaration
}
